learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views


# Template tagging
# https://docs.djangoproject.com/en/3.1/ref/urls/
app_name = 'basic_app'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views


urlpatterns = [
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    context_dict = {'text': 'hello world', 'number':100}
    return render(request, 'basic_app/index.html', context_dict)


def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <title>Title</title>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">Brand</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            <a class="nav-link" href="{% url 'basic_app:other' %}">Other</a>
            <a class="nav-link" href="{% url 'basic_app:relative' %}">Relative</a>
          </div>
        </div>
      </div>
    </nav>

    <div class="container">

        {% block body_block %}
<!--        Anything outside of this will be inherited-->
        {% endblock %}

    </div>
</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
        <h1>Welcome to index</h1>
        <h2>This is index.html page showing</h2>
        <h3>
            {{ text|cut:'world' }}
            {{ number|add:"25" }}
        </h3>
    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
    <h1>Welcome to other</h1>
    <h2>This is an example of template inheritance</h2>
    {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Welcome to relative url templates</h1>
<!--note below that the 'basic_app' refers to the name defined in basic_app/urls.py
    NOT to the folder.  Similarly the 'other' is also the name in the basic_app/urls.py file   -->
    <a href="{% url 'basic_app:other' %}">The other page</a>
    <a href="{% url 'admin:index' %}">Link to admin</a>
    <a href="{% url 'index' %}">Link to index</a>
</body>
</html>